version: '3'
services:
  node:
    build: .
    depends_on:
      - 'mongo'
    ports:
      - 1238:1238
  mongo:
    image: mongo
    logging:
      driver: none
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: